src/ShopBundle/Entity/PurchaseHistory.php
<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * PurchaceHistory
 *
 * @ORM\Table(name="purchase_history")
 * @ORM\Entity(repositoryClass="ShopBundle\Repository\PurchaseHistoryRepository")
 */
class PurchaseHistory
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="customer_account_id", type="integer")
     * @NotBlank()
     */
    private $customer_account_id;

    /**
     * @var CustomerAccount
     * @ORM\ManyToOne(targetEntity="ShopBundle\Entity\CustomerAccount")
     * @ORM\JoinColumn(name="customer_account_id", referencedColumnName="id")
     * @NotBlank()
     */
    private $customer_account;

    /**
     * @var int
     *
     * @ORM\Column(name="product_id", type="integer")
     * @NotBlank()
     */
    private $product_id;

    /**
     * @var Product
     * @ORM\ManyToOne(targetEntity="ShopBundle\Entity\Product")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id")
     */
    private $product;

    /**
     * @var int
     *
     * @ORM\Column(name="quantity", type="integer")
     * @NotBlank()
     * @GreaterThanOrEqual(0)
     */
    private $quantity;

    /**
     * @var string
     * @ORM\Column(name="spent", type="decimal", precision=10, scale=0)
     */
    private $amount;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_created", type="datetime")
     */
    private $dateCreated;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set customerId
     *
     * @param $customer_account_id
     * @return PurchaseHistory
     *
     */
    public function setCustomerId($customer_account_id)
    {
        $this->customer_account_id = $customer_account_id;

        return $this;
    }

    /**
     * Get customerId
     *
     * @return int
     */
    public function getCustomerId()
    {
        return $this->customer_account_id;
    }

    /**
     * Set productId
     *
     * @param $product_id
     * @return PurchaseHistory
     *
     */
    public function setProductId($product_id)
    {
        $this->product_id = $product_id;

        return $this;
    }

    /**
     * Get productId
     *
     * @return int
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     *
     * @return PurchaseHistory
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set dateCreated
     *
     * @param \DateTime $dateCreated
     *
     * @return PurchaseHistory
     */
    public function setDateCreated($dateCreated)
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    /**
     * Get dateCreated
     *
     * @return \DateTime
     */
    public function getDateCreated()
    {
        return $this->dateCreated;
    }

    /**
     * @return CustomerAccount
     */
    public function getCustomerAccount()
    {
        return $this->customer_account;
    }

    /**
     * @param CustomerAccount $customer_account
     * @return $this
     */
    public function setCustomerAccount(CustomerAccount $customer_account)
    {
        $this->customer_account = $customer_account;

        return $this;
    }

    /**
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @param string $amount
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * @return Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * @param Product $product
     * @return $this
     */
    public function setProduct($product)
    {
        $this->product = $product;

        return $this;
    }
}

src/ShopBundle/Controller/PurchaseHistoryController.php
<?php

namespace ShopBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use ShopBundle\Entity\CustomerAccount;
use ShopBundle\Entity\PurchaseHistory;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class PurchaseHistoryController extends Controller
{
    /**
     * @Route("/purchaseHistory/own", name="own_purchase_history_list")
     * @Method("GET")
     * @Template
     */
    public function listOwnAction() {
        $user_id = $this
            ->getUser()
            ->getId();
        $customer_account_id = $this
            ->getDoctrine()
            ->getRepository(CustomerAccount::class)
            ->findOneBy(['user_id' => $user_id])
            ->getId();

        $purchase_history = $this
            ->getDoctrine()
            ->getRepository(PurchaseHistory::class)
            ->findBy(['customer_account_id' => $customer_account_id]);
        return [
            'purchase_history' => $purchase_history
        ];
    }

    /**
     * @Route("/purchaseHistory/{id}", name="purchase_history_get")
     * @Method("GET")
     * @Template()
     * @param Request $request
     * @return array
     */
    public function getAction(Request $request)
    {
        $id = $request->attributes->get('id');

        $purchase_history = $this
            ->getDoctrine()
            ->getRepository(PurchaseHistory::class)
            ->find($id);

        return [
            'purchase_history' => $purchase_history
        ];
    }

    /**
     * @Route("/purchaseHistory", name="purchase_history_list")
     * @Method("GET")
     * @Template()
     */
    public function listAction()
    {
        $purchase_history = $this
            ->getDoctrine()
            ->getRepository(PurchaseHistory::class)
            ->findAll();

        $total_amount = 0;

        foreach($purchase_history as $item) {
            $total_amount += ($item->getAmount() * $item->getQuantity());
        }

        return [
            'purchase_history' => $purchase_history,
            'total_amount' => $total_amount
        ];
    }

    /**
     * @Route("/purchaseHistory/customer/{customer_account_id}", name="customer_purchase_history_list")
     * @Method("GET")
     * @Template
     * @param Request $request
     * @return array
     */
    public function listByCustomerAction(Request $request) {
        $customer_account_id = $request->attributes->get('customer_account_id');

        $purchase_history = $this
            ->getDoctrine()
            ->getRepository(PurchaseHistory::class)
            ->findBy(['customer_account_id' => $customer_account_id]);

        $total_amount = 0;

        foreach($purchase_history as $item) {
            $total_amount += ($item->getAmount() * $item->getQuantity());
        }

        return [
            'purchase_history' => $purchase_history,
            'total_amount' => $total_amount
        ];
    }
}

src/ShopBundle/Resources/views/PurchaseHistory/get.html.twig
{% extends "::base.html.twig" %}

{% block title %}ShopBundle:PurchaceHistory:get{% endblock %}

{% block body %}

    <div class="col-md-6">
        <h3>
            Purchase # {{ purchase_history.getId }}
        </h3>
    </div>

{% endblock %}

src/ShopBundle/Resources/views/PurchaseHistory/list.html.twig
{% extends "::base.html.twig" %}

{% block title %}ShopBundle:PurchaceHistory:list{% endblock %}

{% block body %}
<div class="flex justify-center">
    <div class="col-md-10 well">
        <legend>
            {% if purchase_history|length < 1 %}
                No purchase history
            {% else %}
                Purchase history report
            {% endif %}
        </legend>
        {% if purchase_history|length > 0 %}
            <table class="table table-striped table-hover ">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Customer</th>
                    <th>Date of Purchase</th>
                    <th>Product</th>
                    <th class="text-right">Quantity</th>
                    <th class="text-right">Price</th>
                    <th class="text-right">Amount</th>
                </tr>
                </thead>
                <tbody>
                {% for item in purchase_history %}
                    <tr>
                        <td>
                            <a href="{{ path('purchase_history_get', {'id': item.getId}) }}">
                                {{ item.getId }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ path('user_get', {'id': item.customerAccount.getUser.getId}) }}">
                                {{ item.customerAccount.getUser.getUsername }}
                            </a>
                        </td>
                        <td>
                            {{ item.getDateCreated.format('Y-m-d') }}
                        </td>
                        <td>
                            <a href="{{ path('product_get', {'id': item.getProduct.getId}) }}">
                                {{ item.getProduct.getName }}
                            </a>
                        </td>
                        <td class="text-right">
                            {{ item.getQuantity }}
                        </td>
                        <td class="text-right">
                            $ {{ item.getAmount }}
                        </td>
                        <td class="text-right">
                            $ {{ item.getAmount * item.getQuantity }}
                        </td>
                    </tr>
                {% endfor %}
                <tr/>
                <tr>
                    <td/>
                    <td/>
                    <td/>
                    <td/>
                    <td/>
                    <td/>
                    <td class="text-right">
                        Total $ {{ total_amount }}
                    </td>
                </tr>
                </tbody>
            </table>
        {% endif %}
    </div>
</div>
{% endblock %}

src/ShopBundle/Resources/views/PurchaseHistory/listByCustomer.html.twig
{% extends "::base.html.twig" %}

{% block title %}ShopBundle:PurchaceHistory:list{% endblock %}

{% block body %}
    <div class="col-md-6">
        <legend>
            {% if purchase_history|length < 1 %}
                No purchase history
            {% else %}
                Purchase history for user <a href="{{ path('user_get', {'id': purchase_history[0].getCustomerAccount.getUser.getUsername}) }}">
                    {{ purchase_history[0].getCustomerAccount.getUser.getUsername }}
                </a>
            {% endif %}

        </legend>
        {% if purchase_history|length > 0 %}
            <table class="table table-striped table-hover ">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Date of Purchase</th>
                    <th>Product</th>
                    <th class="text-right">Quantity</th>
                    <th class="text-right">Price</th>
                    <th class="text-right">Amount</th>
                </tr>
                </thead>
                <tbody>
                {% for item in purchase_history %}
                    <tr>
                        <td>
                            <a href="{{ path('purchase_history_get', {'id': item.getId}) }}">
                                {{ item.getId }}
                            </a>
                        </td>
                        <td>
                            {{ item.getDateCreated.format('Y-m-d') }}
                        </td>
                        <td>
                            <a href="{{ path('product_get', {'id': item.getProduct.getId}) }}">
                                {{ item.getProduct.getName }}
                            </a>
                        </td>
                        <td class="text-right">
                            {{ item.getQuantity }}
                        </td>
                        <td class="text-right">
                            $ {{ item.getAmount }}
                        </td>
                        <td class="text-right">
                            $ {{ item.getAmount * item.getQuantity }}
                        </td>
                    </tr>
                {% endfor %}
                <tr/>
                <tr>
                    <td/>
                    <td/>
                    <td/>
                    <td/>
                    <td/>
                    <td class="text-right">
                        Total $ {{ total_amount }}
                    </td>
                </tr>
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}

src/ShopBundle/Resources/views/PurchaseHistory/listOwn.html.twig
{% extends "::base.html.twig" %}

{% block title %}ShopBundle:PurchaceHistory:list{% endblock %}

{% block body %}
    <div class="flex justify-center">
        <div class="col-md-10 well">
            <legend>
            {% if purchase_history|length < 1 %}
                No purchase history
            {% else %}
                Purchase history report
            </legend>
            <table class="table table-striped table-hover ">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Date of Purchase</th>
                    <th>Product</th>
                    <th class="text-right">Quantity</th>
                    <th class="text-right">Amount</th>
                    <th class="text-right">Total</th>
                </tr>
                </thead>
                <tbody>
                {% for item in purchase_history %}
                    <tr>
                        <td>
                            <a href="{{ path('purchase_history_get', {'id': item.getId}) }}">
                                {{ item.getId }}
                            </a>
                        </td>
                        <td>
                            {{ item.getDateCreated.format('Y-m-d') }}
                        </td>
                        <td>
                            <a href="{{ path('product_get', {'id': item.getProduct.getId}) }}">
                                {{ item.getProduct.getName }}
                            </a>
                        </td>
                        <td class="text-right">
                            {{ item.getQuantity }}
                        </td>
                        <td class="text-right">
                            $ {{ item.getAmount }}
                        </td>
                        <td class="text-right">
                            $ {{ item.getAmount * item.getQuantity }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
{% endblock %}